# CD workflow
#
# This workflow runs the project's CD pipeline whenever a pull request is merged

name: CD

on:
  pull_request:
    types: 
    - closed
  workflow_dispatch:

# Use Bash as the default shell for all run commands in this workflow.
defaults:
  run:
    shell: bash

# Give the workflow read-only access to the repository contents.
# This is enough for checking out the code and running tests.
permissions:
  contents: read

jobs:
  ci-pipeline:
    # Human-readable name shown in the GitHub Actions UI.
    name: Run CD pipeline

    # Run this job on the self-hosted GitHub Actions runner.
    runs-on: self-hosted

    steps:
      # Sets this variable on each github runner manually since github environment variables cannot resolve bash environment variables
      - name: Set pipeline state path
        run: echo "PIPELINE_STATE_PATH=$HOME/test-pipeline/state" >> "$GITHUB_ENV"

      - name: Set pipeline log path
        run: echo "PIPELINE_LOG_PATH=$HOME/test-pipeline/logs" >> "$GITHUB_ENV"

      # Make the CD script executable, then run it.
      # The script handles deploying new images to docker.
      - name: Execute cd.sh
        run: |
          chmod +x ./scripts/cd.sh
          ./scripts/cd.sh
